namespace:
  name: demo

replicaCount: 3

image:
  repository: nginx
  tag: alpine

imagePullPolicy: IfNotPresent

requests:
  memory: "256Mi"
  cpu: "50m"

service:
  type: ClusterIP
  port: 8111

configmap:
  name: version
  value: alpine
