namespace:
  name: prod

replicaCount: 2

image:
  repository: nginx
  tag: 1.17.0

requests:
  memory: "256Mi"
  cpu: "70m"

service:
  type: ClusterIP
  port: 80

configmap:
  name: version
  value: 1.17.0
